name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *" # At 12PM UTC+8
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤 1: 检出您的仓库，确保检出的是正确的分支（这里假设是 main）
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: main # 明确指定要检出的分支

      # 步骤 2: 运行同步 action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1 # 推荐使用更新的版本
        with:
          # 上游仓库和分支
          upstream_repo: wangwangit/SubsTracker
          upstream_branch: master
          
          # 您的仓库（目标仓库）和分支
          target_branch: master
          target_token: ${{ secrets.GITHUB_TOKEN }}
          
          # 其他参数
          # 注意：参数名已经根据新版本进行了调整
          pull_args: --allow-unrelated-histories --strategy=ours
          push_args: --no-verify # 将原 git_push_args 的值赋给 push_args
          # git_commit_args 通常不需要特殊设置
          # git_log_format_option 已被移除，可以不设置

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Workflow failed. Please check the logs for details."
          exit 1
