name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 4 * * *" # At 12PM UTC+8
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 步骤 1: 检出您的仓库。请再次确认您的主分支是 'master' 还是 'main'
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: master # 假设您的分支是 master

      # 步骤 2: 运行同步 action，使用正确的参数名
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          # --- 修正点：使用了日志中提示的正确参数名 ---

          # 上游仓库和分支
          upstream_sync_repo: wangwangit/SubsTracker
          upstream_sync_branch: master
          
          # 您的仓库（目标仓库）和分支
          target_sync_branch: master # 假设您的分支是 master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          
          # 其他参数也需要使用正确的名称
          upstream_pull_args: --allow-unrelated-histories --strategy=ours
          target_branch_push_args: --no-verify

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Workflow failed. Please check the logs for details."
          exit 1
